project_id = "tkgpmwlnixizolszvbpc"

[functions.assign-user-role]
verify_jwt = true

[functions.ai-cv-analyzer]
verify_jwt = true

[functions.ai-interview-scheduler]
verify_jwt = true

[functions.ai-interview-evaluator]
verify_jwt = true

[functions.send-followup-email]
verify_jwt = true