project_id = "tkgpmwlnixizolszvbpc"

[functions.freddy-chat]
verify_jwt = false

[functions.penny-chat]
verify_jwt = false

[functions.hilda-chat]
verify_jwt = false

[functions.clara-chat]
verify_jwt = false

[functions.sally-chat]
verify_jwt = false

[functions.ai-interview-token]
verify_jwt = false

[functions.eva-chat]
verify_jwt = false